package DCMS_CORBA;


/**
* DCMS_CORBA/DCMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DCMS_CORBA.idl
* Monday, July 10, 2017 1:30:45 PM EDT
*/

public interface DCMSOperations 
{
  String createDRecord (String managerId, String firstName, String lastName, String address, String phone, String specialization, String location);
  String createNRecord (String managerId, String firstName, String lastName, String designation, String status, String statusDate);
  String getRecordCounts (String managerId, String recordType);
  String editRecord (String managerId, String recordID, String fieldName, String newValue);
  String transferRecord (String managerId, String recordID, String remoteClinicServerName);
} // interface DCMSOperations
