package DCMS_CORBA;

import java.io.IOException;

/**
* DCMS_CORBA/DCMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DCMS_CORBA.idl
* Monday, July 10, 2017 5:36:23 PM EDT
*/

public interface DCMSOperations 
{
  String createTRecord (String managerId, String firstName, String lastName, String address, String phone, String specialization, String location)throws IOException;
  String createSRecord (String managerId, String firstName, String lastName, String courseRegistered, String status, String statusDate)throws IOException;
  String getRecordCounts (String managerId)throws IOException;
  String editRecord (String managerId, String recordID, String fieldName, String newValue)throws IOException;
  String transferRecord (String managerId, String recordID, String remoteCenterServerName)throws IOException;
} // interface DCMSOperations
